[project]
name = "graphrag-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "langchain-ollama>=0.3.4",
    "langchain-surrealdb>=0.1.3",
    "surrealdb>=1.0.4",
]
